Week2 First Modify Servlets
nepecg000/software-product-sprint pull request #5
Opened 2020-07-14 07:13 UTC by nepecg000

Thanks for reviewing. This servlet works under /data URL.

2020-07-15 15:52 UTC, layog reviewed
This contains commits from other PRs. Can you remove those commits?

Also, there is only one new commit in this PR where you add your name after "Hello World". The title of the PR does not match the content here

2020-07-20 11:34 UTC, layog requested changes
Hi Hsin-mei,

This PR still contains commits from the other PR, while merging it will give you lots of merge conflicts. So I suggest to fix this first. If you have trouble, I'll explain how to do this in our meeting this time.

Can you deploy this version as well? I cannot see the comments feature on the deployed version.

2020-07-23 06:58 UTC, nepecg000 commented
I tried to fix the problem by rebasing week2 from week1 to master. However, it seems that every file that week1 creates, but week2 doesn't modify it, was deleted.

2020-07-23 07:30 UTC, layog commented
Okay, let's do one thing, merge the PR#4, I have approved that, then pull the master locally and try rebasing to master again.

2020-07-23 08:10 UTC, nepecg000 commented
This looks more making sense now. Please review it and see if that's right.

2020-07-23 16:13 UTC, layog approved these changes
I like the readability of your code, really well written. LGTM

2020-07-23 16:13 UTC, layog commented on portfolio/src/main/webapp/index.html
> +        <script src="./script.js"/>
nit: AFAIK we do not prefer relative paths in HTML. I believe you should change it to absolute path like `src="/script.js"`

2020-07-24 03:22 UTC, merged